version: "3"
services:
  frontail:
    image: mthenw/frontail:latest
    restart: unless-stopped
    container_name: frontail
    volumes:
    - ./log:/log
    command: ["/log/hosts/*/*.log"]
    ports:
      - 9001:9001
    healthcheck:
      test: ["CMD-SHELL", "ls", "/log/hosts/*/*.log"]
      interval: 5s
      timeout: 10s
      retries: 10
  rsyslog:
    image: rsyslog/syslog_appliance_alpine
    volumes:
      - ./rsyslog/container_config:/config/container_config 
      - ./log:/logs
    ports:
      - 514:514
  samplenginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
    - 127.0.0.1:80:80
